exec: Fix compiler warning (-Werror=clobbered)
gcc 4.7 shows a new warning when -Wclobbered (which is part of -Wextra) is
enabled:

qemu/exec.c:921:11: error:
 variable ‘area’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]

The warning is caused by sigsetjmp which was added in commit
ef36fa1492e9105f3fa607b56edc63df513d7da1.

Declaring the variable with attribute 'volatile' fixes the warning.

Signed-off-by: Stefan Weil <sw@weilnetz.de>