.travis.yml: disable Sparse testing
On travis-ci.org, all builds fail with
   /usr/include/features.h:324:11: error: unable to open bits/predefs.h

With "make docker-travis@ubuntu", they fail with
   /usr/include/features.h:374:13: error: unable to open sys/cdefs.h

With "make docker-travis@fedora", finally, they fail due to sparse
not being able to parse some #pragmas in glib headers.  Just kill
the thing from the CI builds.

Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
[AJB: tweak title for my OCD]
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>