simpletrace: suppress a warning from unused variable
Avoid this warning:
  CC    simpletrace.o
/src/qemu/simpletrace.c: In function 'writeout_thread':
/src/qemu/simpletrace.c:122:12: error: variable 'unused' set but not used [-Werror=unused-but-set-variable]
by adding GCC attribute unused to the variable.

Signed-off-by: Blue Swirl <blauwirbel@gmail.com>